### ISSUE TITLE
Error on non-existing elements when deleting activities

### ISSUE THREAD

**Issue by ErikHommel** [systopia/de.systopia.xcm#15] opened 2017-10-12 08:12 UTC
When I try to delete an activity from the contact summary I get the error:

> #5 /var/www/html/aivldev/sites/all/modules/civicrm/packages/HTML/QuickForm.php(791): PEAR->raiseError(NULL, -3, NULL, 512, "Element 'status_id' does not exist in HTML_QuickForm::getElement()", "HTML_QuickForm_Error", TRUE)

I did include the try/catch block that was put around the getElements in a later version, but that does not fix the issue.

**Comment by systopia** [comment] 2017-10-19 13:28
@ErikHommel: I would assume it's the "diff helper" which is marked as 'beta'. Does the problem persist if you turn it off (xcm configuration)?

**Comment by ErikHommel** [comment] 2017-10-19 13:45
Could well be - but I did a PR with a fix too :-)

**Comment by systopia** [comment] 2017-10-19 13:56
I've seen it, just wanted to verify that the diff helper was the cause

**Comment by ErikHommel** [comment] 2017-10-19 14:35
I do not remember exactly but I can try to switch off my fix and then see if the problem persists.

**Comment by ErikHommel** [comment] 2017-11-06 10:42
Yes, the cause is the diff helper. No problems if I switch it off.

**Closed** 2018-06-15 09:17 UTC
Labels: bug
