### ISSUE TITLE
Error at AIVL with FormProcessor 1.13 and ActionProvider 1.81

### ISSUE THREAD

**Issue by ErikHommel** [systopia/de.systopia.xcm#89] opened 2021-09-30 12:43 UTC
At AIVL the following error occurs with OneOff and Recurring donation form processors in XCM action: 
"error_message": "Action Identify Contact failed. Caused by country_id requires a single value a multiple value is given" .

**Comment by bjendres** [comment] 2021-10-04 07:24
This error message is coming from the action provider ([HERE](https://lab.civicrm.org/extensions/action-provider/-/blob/1.82/Civi/ActionProvider/Parameter/Specification.php#L325)), so the problem is most likely in the input data. XCM defines ``country_id`` as a single value ([HERE](https://github.com/systopia/de.systopia.xcm/blob/1.8/Civi/Xcm/ActionProvider/Action/ContactGetOrCreate.php#L86)), so presumably the input value passed to the action in your case is an array.

@ErikHommel could you confirm that?

**Comment by ErikHommel** [comment] 2021-10-04 08:07
Yes, the input data is an array but NOT specified as an array in the Form
Processor. I think it is because of a fix in the ActionProvider but I will
have to check in a little more detail.

met vriendelijke groet,
Erik Hommel

E: ***@***.***
T: +31 (0)6 30 05 40 96




Op ma 4 okt. 2021 om 09:25 schreef Björn Endres ***@***.***>:

**Comment by bjendres** [comment] 2021-11-29 12:31
I have now applied @ErikHommel's patch (https://github.com/ErikHommel/de.systopia.xcm/pull/1) to branch ``issue/89`` to test this.

**Comment by bjendres** [comment] 2022-05-03 17:35
Unfortunately, I will have to revert the changes, because it was causing issues with the *current* versions of ActionProvider and FormProcessor.

@ErikHommel If that means that your problem will pop up again, let's have a look together where it's actually coming from. ``country_id`` really shouldn't be passed as an array from the input side.

**Comment by bjendres** [comment] 2024-06-27 11:17
Will close this for now, feel free to re-open if this is still happening.

**Closed by bjendres** 2024-06-27 11:17 UTC
Labels: invalid
