### ISSUE TITLE
When Override details is set the data is not added to the diff activity

### ISSUE THREAD

**Issue by jaapjansma** [systopia/de.systopia.xcm#62] opened 2020-06-19 12:40 UTC
When one sets a override field and/or override details. Then this data is not added to the diff activity.

**Expected behaviour**
The diff activity is created listing the old data and the submitted data
The submitted data is stored at the contact, overriding existing data.

**Current behaviour**
The data is overridden at the contact record but not listed in the diff activity.

**Comment by jensschuppe** [comment] 2020-06-19 13:01
@bjendres Isn't that expected behavior, since the diff activity should only include changes that haven't been applied instantly by XCM?

Quoting from the [docs](https://docs.civicrm.org/xcm/en/latest/configuration/#difference-handling):
> This section defines, what to do when a contact has been identified by XCM, submitted data was different to the contact's current state, and those different properties have not been changed by XCM.

**Comment by bjendres** [comment] 2020-06-19 14:03
closing this in favour of #64

**Closed by bjendres** 2020-06-19 14:03 UTC
